name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - feat/python_bindings

defaults:
  run:
    working-directory: python


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # platform: [windows-latest, macos-latest, macos-13, ubuntu-latest]
        platform: [ubuntu-latest]
        # python-version: ["3.11", "3.12"]
        python-version: ["3.11"]

    runs-on: ${{ matrix.platform }}
    if: "contains(github.event.head_commit.message, '+ci')"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add requirements
      run: python -m pip install --upgrade wheel setuptools pybind11>=2.12.0 build

    - name: Build and install
      env:
        FORCE_AVX2: "1"
      run: python3 -m build

    - name: Test
      run: python -m pytest

    - name: Test dist
      run: |
        ls
        ls dist

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-dists
        path: dist/

  pypi-publish:
    runs-on: "ubuntu-latest"

    needs:
      - build

    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    # Dedicated environments with protections for publishing are strongly recommended.
    environment:
      name: testpypi
      # OPTIONAL: uncomment and update to include your PyPI project URL in the deployment status:
      url: https://test.pypi.org/project/deglib/

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1